# Bibliografía y recursos {.unnumbered}

<!-- ::: {#refs}
::: -->

## Libros

- Cascales, B. y otros (2003). _El libro de Latex_. Pearson Educación.
- Cascales, B. y otros (2000). _LaTeX: una imprenta en sus manos_. Aula Documental de Investigación.
- Lamport, Leslie (1994). _LaTeX: A Document Preparation System_, 2nd Edition. 2nd ed. Addison-Wesley Professional. .
- Mittelbach, F. et al. (2004). _LaTeX Companion, The, 2nd Edition_. 2nd ed. Addison-Wesley Professional.
- Oetiker, T et al (2021). [_The not so short introduction to LaTeX 2e_](https://tobi.oetiker.ch/lshort/lshort.pdf)

## Sitios Web

- [The $\text{\LaTeX}$ project](https://www.latex-project.org/). Sito web principal del proyecto $\text{\LaTeX}$ con multitud de materiales para aprender y noticias sobre el desarrollo de nuevas versiones.
- [Comprehensive $\text{\TeX}$ Archive Network](https://ctan.org/). Principal repositorios de paquetes para $\text{\TeX}$ y $\text{\LaTeX}$.
- [CervanTeX](www.cervantex.es/). Grupos de usuarios de TeX hispanoablantes.
- [Awesome LaTeX](https://project-awesome.org/egeerardyn/awesome-LaTeX). Sitio web con multitud de recursos curados para escribir documentos con $\text{\LaTeX}$.
- [Chuleta de $\text{\LaTeX}$](chulatex.pdf). Resumen de los principales comandos y entornos de $\text{\LaTeX}$.